# Generated by Django 4.2.5 on 2023-09-18 18:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Post Title')),
                ('img', models.ImageField(default='post_img/default_img.jpg', upload_to='post_img/')),
                ('content', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, help_text='You Can Avoid This Field if Unnessery', max_length=50, null=True)),
                ('url', models.SlugField(blank=True, help_text='This Field Automatic Generated based on post Category & Post Title. Also You can create Custom url.', unique=True)),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.category', verbose_name='Post Category')),
            ],
        ),
    ]
