# Generated by Django 4.2.5 on 2023-09-18 19:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0002_alter_category_title_alter_post_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Post Title')),
                ('img', models.ImageField(default='post_img/default_img.jpg', upload_to='post_img/feature_post', verbose_name='Feature Post Image')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, help_text='You Can Avoid This Field if Unnessery', max_length=255, null=True, verbose_name='Post Tag')),
                ('url', models.SlugField(blank=True, help_text='This Field Automatic Generated based on post Category & Post Title. Also You can create Custom url.', unique=True, verbose_name='Post Url (Optional)')),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.category', verbose_name='Post Category')),
            ],
            options={
                'verbose_name': 'FeaturePost',
                'verbose_name_plural': 'FeaturePosts',
            },
        ),
    ]
